# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscreen.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
#from openbreaker import Ui_OpenBreaker


class Ui_MainWindow(object):
    def clickA1(self):
        print("A1 Clicked")
    def clickA2(self):
        print("A2 Clicked")
    def clickA3(self):
        print("A3 Clicked")   
    def clickA4(self):
        print("A4 Clicked")
    def clickAMom(self):
        print("A-mom Clicked")
    def clickJ1(self):
        print("J1 Clicked")
    def clickJ2(self):
        print("J2 Clicked")
    def clickJ3(self):
        print("J3 Clicked")
    def clickJ4(self):
        print("J4 Clicked")     
    def clickJMom(self):
        print("J-mom Clicked")
    def clickP1(self):
        print("P1 Clicked")
    def clickP2(self):
        print("P2 Clicked")
    def clickP3(self):
        print("P3 Clicked")
    def clickP4(self):
        print("P4 Clicked")
    def clickPMom(self):
        print("P-mom Clicked")
    def clickD1(self):
        print("D1 Clicked")
    def clickD2(self):
        print("D2 Clicked")
    def clickD3(self):
        print("D3 Clicked")
    def clickD4(self):
        print("D4 Clicked")
    def clickDMom(self):
        print("D-mom Clicked")
    def clickK1(self):
        print("K1 Clicked")
    def clickK2(self):
        print("K2 Clicked")
    def clickK3(self):
        print("K3 Clicked")
    def clickK4(self):
        print("K4 Clicked")
    def clickKMom(self):
        print("K-mom Clicked")
    def clickQ1(self):
        print("Q1 Clicked")
    def clickQ2(self):
        print("Q2 Clicked")
    def clickQ3(self):
        print("Q3 Clicked")
    def clickQ4(self):
        print("Q4 Clicked")
    def clickQMom(self):
        print("Q-mom Clicked")
    def clickS1(self):
        print("S1 Clicked")
    def clickSMom(self):
        print("S-mom Clicked")
        
            
#    def openbreakerShow(self):
#        self.openbreakerWindow = QtGui.QDialog()
#        self.ui = Ui_OpenBreaker()
#        self.ui.setupUi(self.openbreakerWindow)
#        self.openbreakerWindow.show()
#        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 601)
        MainWindow.setMinimumSize(QtCore.QSize(916, 601))
        MainWindow.setMaximumSize(QtCore.QSize(916, 601))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.brkr3_A = QtWidgets.QPushButton(self.centralwidget)
        self.brkr3_A.setGeometry(QtCore.QRect(160, 110, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr3_A.setFont(font)
        self.brkr3_A.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr3_A.setObjectName("brkr3_A")
        #-----------------Buttun event-------------
        self.brkr3_A.clicked.connect(self.clickA3)
        #---------------------------------------------
        self.brkr2_A = QtWidgets.QPushButton(self.centralwidget)
        self.brkr2_A.setGeometry(QtCore.QRect(80, 110, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr2_A.setFont(font)
        self.brkr2_A.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr2_A.setObjectName("brkr2_A")
        #-----------Button event ---------------------
        self.brkr2_A.clicked.connect(self.clickA2)
        #---------------------------------------------
        self.brkr1_A = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_A.setGeometry(QtCore.QRect(120, 70, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_A.setFont(font)
        self.brkr1_A.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_A.setObjectName("brkr1_A")
        ############ Button Event ##############
        self.brkr1_A.clicked.connect(self.clickA1)
        ########################################
        self.brkr4_A = QtWidgets.QPushButton(self.centralwidget)
        self.brkr4_A.setGeometry(QtCore.QRect(120, 150, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr4_A.setFont(font)
        self.brkr4_A.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr4_A.setObjectName("brkr4_A")
        ############ Button Event ##############
        self.brkr4_A.clicked.connect(self.clickA4)
        ########################################
        self.mother_ace = QtWidgets.QPushButton(self.centralwidget)
        self.mother_ace.setGeometry(QtCore.QRect(30, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_ace.setFont(font)
        self.mother_ace.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_ace.setObjectName("mother_ace")
        ############ Button Event ##############
        self.mother_ace.clicked.connect(self.clickAMom)
        ########################################
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(100, 170, 81, 3))
        self.line_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(170, 90, 20, 81))
        self.line_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(100, 80, 81, 16))
        self.line_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(90, 90, 20, 81))
        self.line_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.brkr2_K = QtWidgets.QPushButton(self.centralwidget)
        self.brkr2_K.setGeometry(QtCore.QRect(80, 430, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr2_K.setFont(font)
        self.brkr2_K.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr2_K.setObjectName("brkr2_K")
        ############ Button Event ##############
        self.brkr2_K.clicked.connect(self.clickK2)
        ########################################
        self.mother_king = QtWidgets.QPushButton(self.centralwidget)
        self.mother_king.setGeometry(QtCore.QRect(30, 500, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_king.setFont(font)
        self.mother_king.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_king.setObjectName("mother_king")
        ############ Button Event ##############
        self.mother_king.clicked.connect(self.clickKMom)
        ########################################
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(170, 410, 20, 81))
        self.line_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(100, 410, 81, 3))
        self.line_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(100, 490, 81, 3))
        self.line_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.brkr4_K = QtWidgets.QPushButton(self.centralwidget)
        self.brkr4_K.setGeometry(QtCore.QRect(120, 470, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr4_K.setFont(font)
        self.brkr4_K.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr4_K.setObjectName("brkr4_K")
        ############ Button Event ##############
        self.brkr4_K.clicked.connect(self.clickK4)
        ########################################
        self.brkr3_K = QtWidgets.QPushButton(self.centralwidget)
        self.brkr3_K.setGeometry(QtCore.QRect(160, 430, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr3_K.setFont(font)
        self.brkr3_K.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr3_K.setObjectName("brkr3_K")
        ############ Button Event ##############
        self.brkr3_K.clicked.connect(self.clickK3)
        ########################################
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(90, 410, 20, 81))
        self.line_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.brkr1_K = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_K.setGeometry(QtCore.QRect(120, 390, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_K.setFont(font)
        self.brkr1_K.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_K.setObjectName("brkr1_K")
        ############ Button Event ##############
        self.brkr1_K.clicked.connect(self.clickK1)
        ########################################
        self.brkr2_J = QtWidgets.QPushButton(self.centralwidget)
        self.brkr2_J.setGeometry(QtCore.QRect(230, 210, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr2_J.setFont(font)
        self.brkr2_J.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr2_J.setObjectName("brkr2_J")
        ############ Button Event ##############
        self.brkr2_J.clicked.connect(self.clickJ2)
        ########################################
        self.mother_joker = QtWidgets.QPushButton(self.centralwidget)
        self.mother_joker.setGeometry(QtCore.QRect(350, 280, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_joker.setFont(font)
        self.mother_joker.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_joker.setObjectName("mother_joker")
        ############ Button Event ##############
        self.mother_joker.clicked.connect(self.clickJMom)
        ########################################
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(320, 190, 20, 81))
        self.line_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(250, 190, 81, 3))
        self.line_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(250, 270, 81, 3))
        self.line_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.brkr4_J = QtWidgets.QPushButton(self.centralwidget)
        self.brkr4_J.setGeometry(QtCore.QRect(270, 250, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr4_J.setFont(font)
        self.brkr4_J.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr4_J.setObjectName("brkr4_J")
        ############ Button Event ##############
        self.brkr4_J.clicked.connect(self.clickJ4)
        ########################################
        self.brkr3_J = QtWidgets.QPushButton(self.centralwidget)
        self.brkr3_J.setGeometry(QtCore.QRect(310, 210, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr3_J.setFont(font)
        self.brkr3_J.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr3_J.setObjectName("brkr3_J")
        ############ Button Event ##############
        self.brkr3_J.clicked.connect(self.clickJ3)
        ########################################
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(240, 190, 20, 81))
        self.line_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setObjectName("line_13")
        self.brkr1_J = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_J.setGeometry(QtCore.QRect(270, 170, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_J.setFont(font)
        self.brkr1_J.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_J.setObjectName("brkr1_J")
        ############ Button Event ##############
        self.brkr1_J.clicked.connect(self.clickJ1)
        ########################################
        self.brkr2_D = QtWidgets.QPushButton(self.centralwidget)
        self.brkr2_D.setGeometry(QtCore.QRect(730, 110, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr2_D.setFont(font)
        self.brkr2_D.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr2_D.setObjectName("brkr2_D")
        ############ Button Event ##############
        self.brkr2_D.clicked.connect(self.clickD2)
        ########################################
        self.mother_deuce = QtWidgets.QPushButton(self.centralwidget)
        self.mother_deuce.setGeometry(QtCore.QRect(840, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_deuce.setFont(font)
        self.mother_deuce.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_deuce.setObjectName("mother_deuce")
        ############ Button Event ##############
        self.mother_deuce.clicked.connect(self.clickDMom)
        ########################################
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(820, 90, 20, 81))
        self.line_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(750, 90, 81, 3))
        self.line_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(750, 170, 81, 3))
        self.line_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.brkr4_D = QtWidgets.QPushButton(self.centralwidget)
        self.brkr4_D.setGeometry(QtCore.QRect(770, 150, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr4_D.setFont(font)
        self.brkr4_D.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr4_D.setObjectName("brkr4_D")
        ############ Button Event ##############
        self.brkr4_D.clicked.connect(self.clickD4)
        ########################################
        self.brkr3_D = QtWidgets.QPushButton(self.centralwidget)
        self.brkr3_D.setGeometry(QtCore.QRect(810, 110, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr3_D.setFont(font)
        self.brkr3_D.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr3_D.setObjectName("brkr3_D")
        ############ Button Event ##############
        self.brkr3_D.clicked.connect(self.clickD3)
        ########################################
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(740, 90, 20, 81))
        self.line_17.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_17.setLineWidth(2)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setObjectName("line_17")
        self.brkr1_D = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_D.setGeometry(QtCore.QRect(770, 70, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_D.setFont(font)
        self.brkr1_D.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_D.setObjectName("brkr1_D")
        ############ Button Event ##############
        self.brkr1_D.clicked.connect(self.clickD1)
        ########################################
        self.brkr2_P = QtWidgets.QPushButton(self.centralwidget)
        self.brkr2_P.setGeometry(QtCore.QRect(590, 210, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr2_P.setFont(font)
        self.brkr2_P.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr2_P.setObjectName("brkr2_P")
        ############ Button Event ##############
        self.brkr2_P.clicked.connect(self.clickP2)
        ########################################
        self.mother_poker = QtWidgets.QPushButton(self.centralwidget)
        self.mother_poker.setGeometry(QtCore.QRect(550, 280, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_poker.setFont(font)
        self.mother_poker.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_poker.setObjectName("mother_poker")
        ############ Button Event ##############
        self.mother_poker.clicked.connect(self.clickPMom)
        ########################################
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(680, 190, 20, 81))
        self.line_18.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_18.setLineWidth(2)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(610, 190, 81, 3))
        self.line_19.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_19.setLineWidth(2)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(610, 270, 81, 3))
        self.line_20.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_20.setLineWidth(2)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setObjectName("line_20")
        self.brkr4_P = QtWidgets.QPushButton(self.centralwidget)
        self.brkr4_P.setGeometry(QtCore.QRect(630, 250, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr4_P.setFont(font)
        self.brkr4_P.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr4_P.setObjectName("brkr4_P")
        ############ Button Event ##############
        self.brkr4_P.clicked.connect(self.clickP4)
        ########################################
        self.brkr3_P = QtWidgets.QPushButton(self.centralwidget)
        self.brkr3_P.setGeometry(QtCore.QRect(670, 210, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr3_P.setFont(font)
        self.brkr3_P.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr3_P.setObjectName("brkr3_P")
        ############ Button Event ##############
        self.brkr3_P.clicked.connect(self.clickP3)
        ########################################
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(600, 190, 20, 81))
        self.line_21.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_21.setLineWidth(2)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setObjectName("line_21")
        self.brkr1_P = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_P.setGeometry(QtCore.QRect(630, 170, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_P.setFont(font)
        self.brkr1_P.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_P.setObjectName("brkr1_P")
        ############ Button Event ##############
        self.brkr1_P.clicked.connect(self.clickP1)
        ########################################
        self.brkr2_Q = QtWidgets.QPushButton(self.centralwidget)
        self.brkr2_Q.setGeometry(QtCore.QRect(730, 430, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr2_Q.setFont(font)
        self.brkr2_Q.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr2_Q.setObjectName("brkr2_Q")
        ############ Button Event ##############
        self.brkr2_Q.clicked.connect(self.clickQ2)
        ########################################
        self.mother_queen = QtWidgets.QPushButton(self.centralwidget)
        self.mother_queen.setGeometry(QtCore.QRect(840, 510, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_queen.setFont(font)
        self.mother_queen.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_queen.setObjectName("mother_queen")
        ############ Button Event ##############
        self.mother_queen.clicked.connect(self.clickQMom)
        ########################################
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(820, 410, 20, 81))
        self.line_22.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_22.setLineWidth(2)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(750, 410, 81, 3))
        self.line_23.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_23.setLineWidth(2)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(750, 490, 81, 3))
        self.line_24.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_24.setLineWidth(2)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setObjectName("line_24")
        self.brkr4_Q = QtWidgets.QPushButton(self.centralwidget)
        self.brkr4_Q.setGeometry(QtCore.QRect(770, 470, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr4_Q.setFont(font)
        self.brkr4_Q.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr4_Q.setObjectName("brkr4_Q")
        ############ Button Event ##############
        self.brkr4_Q.clicked.connect(self.clickQ4)
        ########################################
        self.brkr3_Q = QtWidgets.QPushButton(self.centralwidget)
        self.brkr3_Q.setGeometry(QtCore.QRect(810, 430, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr3_Q.setFont(font)
        self.brkr3_Q.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr3_Q.setObjectName("brkr3_Q")
        ############ Button Event ##############
        self.brkr3_Q.clicked.connect(self.clickQ3)
        ########################################
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(740, 410, 20, 81))
        self.line_25.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_25.setLineWidth(2)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setObjectName("line_25")
        self.brkr1_Q = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_Q.setGeometry(QtCore.QRect(770, 390, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_Q.setFont(font)
        self.brkr1_Q.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_Q.setObjectName("brkr1_Q")
        ############ Button Event ##############
        self.brkr1_Q.clicked.connect(self.clickQ1)
        ########################################
        self.mother_solar = QtWidgets.QPushButton(self.centralwidget)
        self.mother_solar.setGeometry(QtCore.QRect(350, 420, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.mother_solar.setFont(font)
        self.mother_solar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mother_solar.setObjectName("mother_solar")
        ############ Button Event ##############
        self.mother_solar.clicked.connect(self.clickSMom)
        ########################################
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setGeometry(QtCore.QRect(500, 340, 20, 81))
        self.line_26.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_26.setLineWidth(2)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(430, 340, 81, 3))
        self.line_27.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_27.setLineWidth(2)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(430, 420, 81, 3))
        self.line_28.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_28.setLineWidth(2)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.centralwidget)
        self.line_29.setGeometry(QtCore.QRect(420, 340, 20, 81))
        self.line_29.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_29.setLineWidth(2)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setObjectName("line_29")
        self.brkr1_S = QtWidgets.QPushButton(self.centralwidget)
        self.brkr1_S.setGeometry(QtCore.QRect(450, 320, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.brkr1_S.setFont(font)
        self.brkr1_S.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.brkr1_S.setObjectName("brkr1_S")
        ############ Button Event ##############
        self.brkr1_S.clicked.connect(self.clickS1)
        ########################################
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 50, 20, 41))
        self.line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_30 = QtWidgets.QFrame(self.centralwidget)
        self.line_30.setGeometry(QtCore.QRect(70, 40, 31, 16))
        self.line_30.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_30.setLineWidth(2)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setObjectName("line_30")
        self.rf_line = QtWidgets.QFrame(self.centralwidget)
        self.rf_line.setGeometry(QtCore.QRect(180, 80, 571, 20))
        self.rf_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.rf_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rf_line.setLineWidth(2)
        self.rf_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.rf_line.setObjectName("rf_line")
        self.fh_line = QtWidgets.QFrame(self.centralwidget)
        self.fh_line.setGeometry(QtCore.QRect(90, 160, 20, 251))
        self.fh_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.fh_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fh_line.setLineWidth(2)
        self.fh_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.fh_line.setObjectName("fh_line")
        self.line_33 = QtWidgets.QFrame(self.centralwidget)
        self.line_33.setGeometry(QtCore.QRect(90, 490, 16, 41))
        self.line_33.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_33.setLineWidth(2)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.centralwidget)
        self.line_34.setGeometry(QtCore.QRect(70, 520, 31, 16))
        self.line_34.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_34.setLineWidth(2)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setObjectName("line_34")
        self.sf_line = QtWidgets.QFrame(self.centralwidget)
        self.sf_line.setGeometry(QtCore.QRect(180, 480, 571, 20))
        self.sf_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.sf_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sf_line.setLineWidth(2)
        self.sf_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.sf_line.setObjectName("sf_line")
        self.foak_line = QtWidgets.QFrame(self.centralwidget)
        self.foak_line.setGeometry(QtCore.QRect(820, 170, 20, 251))
        self.foak_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.foak_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foak_line.setLineWidth(2)
        self.foak_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.foak_line.setObjectName("foak_line")
        self.line_37 = QtWidgets.QFrame(self.centralwidget)
        self.line_37.setGeometry(QtCore.QRect(830, 480, 31, 20))
        self.line_37.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_37.setLineWidth(2)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.centralwidget)
        self.line_38.setGeometry(QtCore.QRect(850, 490, 20, 21))
        self.line_38.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_38.setLineWidth(2)
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setObjectName("line_38")
        self.line_39 = QtWidgets.QFrame(self.centralwidget)
        self.line_39.setGeometry(QtCore.QRect(850, 70, 20, 21))
        self.line_39.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_39.setLineWidth(2)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setObjectName("line_39")
        self.line_40 = QtWidgets.QFrame(self.centralwidget)
        self.line_40.setGeometry(QtCore.QRect(830, 80, 31, 20))
        self.line_40.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_40.setLineWidth(2)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setObjectName("line_40")
        self.c2_line = QtWidgets.QFrame(self.centralwidget)
        self.c2_line.setGeometry(QtCore.QRect(180, 180, 71, 20))
        self.c2_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.c2_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c2_line.setLineWidth(2)
        self.c2_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.c2_line.setObjectName("c2_line")
        self.c1_line = QtWidgets.QFrame(self.centralwidget)
        self.c1_line.setGeometry(QtCore.QRect(170, 170, 20, 21))
        self.c1_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.c1_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c1_line.setLineWidth(2)
        self.c1_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.c1_line.setObjectName("c1_line")
        self.d2_line = QtWidgets.QFrame(self.centralwidget)
        self.d2_line.setGeometry(QtCore.QRect(680, 170, 20, 21))
        self.d2_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.d2_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.d2_line.setLineWidth(2)
        self.d2_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.d2_line.setObjectName("d2_line")
        self.d1_line = QtWidgets.QFrame(self.centralwidget)
        self.d1_line.setGeometry(QtCore.QRect(690, 160, 61, 20))
        self.d1_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.d1_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.d1_line.setLineWidth(2)
        self.d1_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.d1_line.setObjectName("d1_line")
        self.line_45 = QtWidgets.QFrame(self.centralwidget)
        self.line_45.setGeometry(QtCore.QRect(330, 290, 21, 20))
        self.line_45.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_45.setLineWidth(2)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setObjectName("line_45")
        self.line_46 = QtWidgets.QFrame(self.centralwidget)
        self.line_46.setGeometry(QtCore.QRect(320, 270, 20, 31))
        self.line_46.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_46.setLineWidth(2)
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setObjectName("line_46")
        self.sp_line = QtWidgets.QFrame(self.centralwidget)
        self.sp_line.setGeometry(QtCore.QRect(320, 180, 300, 20))
        self.sp_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.sp_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sp_line.setLineWidth(2)
        self.sp_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.sp_line.setObjectName("sp_line")
        self.line_48 = QtWidgets.QFrame(self.centralwidget)
        self.line_48.setGeometry(QtCore.QRect(590, 290, 21, 20))
        self.line_48.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_48.setLineWidth(2)
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setObjectName("line_48")
        self.line_49 = QtWidgets.QFrame(self.centralwidget)
        self.line_49.setGeometry(QtCore.QRect(600, 260, 20, 41))
        self.line_49.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_49.setLineWidth(2)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setObjectName("line_49")
        self.b1_line = QtWidgets.QFrame(self.centralwidget)
        self.b1_line.setGeometry(QtCore.QRect(320, 260, 110, 20))
        self.b1_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.b1_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b1_line.setLineWidth(2)
        self.b1_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.b1_line.setObjectName("b1_line")
        self.b2_line = QtWidgets.QFrame(self.centralwidget)
        self.b2_line.setGeometry(QtCore.QRect(430, 270, 3, 70))
        self.b2_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.b2_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b2_line.setLineWidth(2)
        self.b2_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.b2_line.setObjectName("b2_line")
        self.line_52 = QtWidgets.QFrame(self.centralwidget)
        self.line_52.setGeometry(QtCore.QRect(380, 420, 50, 3))
        self.line_52.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.line_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_52.setLineWidth(2)
        self.line_52.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_52.setObjectName("line_52")
        self.ace_label = QtWidgets.QLabel(self.centralwidget)
        self.ace_label.setGeometry(QtCore.QRect(170, 42, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ace_label.setFont(font)
        self.ace_label.setObjectName("ace_label")
        self.joker_label = QtWidgets.QLabel(self.centralwidget)
        self.joker_label.setGeometry(QtCore.QRect(260, 132, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.joker_label.setFont(font)
        self.joker_label.setObjectName("joker_label")
        self.deuce_label = QtWidgets.QLabel(self.centralwidget)
        self.deuce_label.setGeometry(QtCore.QRect(710, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.deuce_label.setFont(font)
        self.deuce_label.setObjectName("deuce_label")
        self.king_label = QtWidgets.QLabel(self.centralwidget)
        self.king_label.setGeometry(QtCore.QRect(120, 350, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.king_label.setFont(font)
        self.king_label.setObjectName("king_label")
        self.queen_label = QtWidgets.QLabel(self.centralwidget)
        self.queen_label.setGeometry(QtCore.QRect(670, 395, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.queen_label.setFont(font)
        self.queen_label.setObjectName("queen_label")
        self.poker_label = QtWidgets.QLabel(self.centralwidget)
        self.poker_label.setGeometry(QtCore.QRect(590, 143, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.poker_label.setFont(font)
        self.poker_label.setObjectName("poker_label")
        self.solar_label = QtWidgets.QLabel(self.centralwidget)
        self.solar_label.setGeometry(QtCore.QRect(520, 370, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.solar_label.setFont(font)
        self.solar_label.setObjectName("solar_label")
        self.h2_line = QtWidgets.QFrame(self.centralwidget)
        self.h2_line.setGeometry(QtCore.QRect(177, 260, 91, 20))
        self.h2_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.h2_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.h2_line.setLineWidth(2)
        self.h2_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.h2_line.setObjectName("h2_line")
        self.h1_line = QtWidgets.QFrame(self.centralwidget)
        self.h1_line.setGeometry(QtCore.QRect(170, 270, 20, 141))
        self.h1_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.h1_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.h1_line.setLineWidth(2)
        self.h1_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.h1_line.setObjectName("h1_line")
        self.k2_line = QtWidgets.QFrame(self.centralwidget)
        self.k2_line.setGeometry(QtCore.QRect(740, 270, 20, 141))
        self.k2_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.k2_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.k2_line.setLineWidth(2)
        self.k2_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.k2_line.setObjectName("k2_line")
        self.k1_line = QtWidgets.QFrame(self.centralwidget)
        self.k1_line.setGeometry(QtCore.QRect(690, 260, 61, 20))
        self.k1_line.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 0, 0);")
        self.k1_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.k1_line.setLineWidth(2)
        self.k1_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.k1_line.setObjectName("k1_line")
        self.line_4.raise_()
        self.mother_ace.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_5.raise_()
        self.brkr1_A.raise_()
        self.brkr4_A.raise_()
        self.mother_king.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.brkr4_K.raise_()
        self.line_9.raise_()
        self.brkr1_K.raise_()
        self.mother_joker.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.brkr4_J.raise_()
        self.line_13.raise_()
        self.brkr1_J.raise_()
        self.mother_deuce.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.brkr4_D.raise_()
        self.line_17.raise_()
        self.brkr1_D.raise_()
        self.mother_poker.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.brkr4_P.raise_()
        self.line_21.raise_()
        self.brkr1_P.raise_()
        self.mother_queen.raise_()
        self.line_22.raise_()
        self.line_23.raise_()
        self.line_24.raise_()
        self.brkr4_Q.raise_()
        self.line_25.raise_()
        self.brkr1_Q.raise_()
        self.brkr2_P.raise_()
        self.line_26.raise_()
        self.line_27.raise_()
        self.line_28.raise_()
        self.line_29.raise_()
        self.brkr1_S.raise_()
        self.line.raise_()
        self.line_30.raise_()
        self.rf_line.raise_()
        self.fh_line.raise_()
        self.line_33.raise_()
        self.line_34.raise_()
        self.sf_line.raise_()
        self.foak_line.raise_()
        self.line_37.raise_()
        self.line_38.raise_()
        self.line_39.raise_()
        self.line_40.raise_()
        self.c2_line.raise_()
        self.c1_line.raise_()
        self.d2_line.raise_()
        self.d1_line.raise_()
        self.line_45.raise_()
        self.line_46.raise_()
        self.sp_line.raise_()
        self.line_48.raise_()
        self.line_49.raise_()
        self.b1_line.raise_()
        self.b2_line.raise_()
        self.line_52.raise_()
        self.mother_solar.raise_()
        self.ace_label.raise_()
        self.joker_label.raise_()
        self.deuce_label.raise_()
        self.king_label.raise_()
        self.queen_label.raise_()
        self.poker_label.raise_()
        self.solar_label.raise_()
        self.h2_line.raise_()
        self.h1_line.raise_()
        self.k2_line.raise_()
        self.k1_line.raise_()
        self.brkr3_P.raise_()
        self.brkr2_K.raise_()
        self.brkr2_J.raise_()
        self.brkr3_K.raise_()
        self.brkr2_A.raise_()
        self.brkr2_Q.raise_()
        self.brkr3_D.raise_()
        self.brkr2_D.raise_()
        self.brkr3_J.raise_()
        self.brkr3_A.raise_()
        self.brkr3_Q.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 21))
        self.menubar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.164, y1:0.193636, x2:0.954545, y2:0.937, stop:0.176136 rgba(170, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAdmin.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Power Lab 4.0"))
        self.brkr3_A.setText(_translate("MainWindow", "3"))
        self.brkr2_A.setText(_translate("MainWindow", "2"))
        self.brkr1_A.setText(_translate("MainWindow", "1"))
        self.brkr4_A.setText(_translate("MainWindow", "4"))
        self.mother_ace.setText(_translate("MainWindow", "Mother"))
        self.brkr2_K.setText(_translate("MainWindow", "2"))
        self.mother_king.setText(_translate("MainWindow", "Mother"))
        self.brkr4_K.setText(_translate("MainWindow", "4"))
        self.brkr3_K.setText(_translate("MainWindow", "3"))
        self.brkr1_K.setText(_translate("MainWindow", "1"))
        self.brkr2_J.setText(_translate("MainWindow", "2"))
        self.mother_joker.setText(_translate("MainWindow", "Mother"))
        self.brkr4_J.setText(_translate("MainWindow", "4"))
        self.brkr3_J.setText(_translate("MainWindow", "3"))
        self.brkr1_J.setText(_translate("MainWindow", "1"))
        self.brkr2_D.setText(_translate("MainWindow", "2"))
        self.mother_deuce.setText(_translate("MainWindow", "Mother"))
        self.brkr4_D.setText(_translate("MainWindow", "4"))
        self.brkr3_D.setText(_translate("MainWindow", "3"))
        self.brkr1_D.setText(_translate("MainWindow", "1"))
        self.brkr2_P.setText(_translate("MainWindow", "2"))
        self.mother_poker.setText(_translate("MainWindow", "Mother"))
        self.brkr4_P.setText(_translate("MainWindow", "4"))
        self.brkr3_P.setText(_translate("MainWindow", "3"))
        self.brkr1_P.setText(_translate("MainWindow", "1"))
        self.brkr2_Q.setText(_translate("MainWindow", "2"))
        self.mother_queen.setText(_translate("MainWindow", "Mother"))
        self.brkr4_Q.setText(_translate("MainWindow", "4"))
        self.brkr3_Q.setText(_translate("MainWindow", "3"))
        self.brkr1_Q.setText(_translate("MainWindow", "1"))
        self.mother_solar.setText(_translate("MainWindow", "Mother"))
        self.brkr1_S.setText(_translate("MainWindow", "1"))
        self.ace_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Ace</span></p></body></html>"))
        self.joker_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Joker</span></p></body></html>"))
        self.deuce_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Deuce</span></p></body></html>"))
        self.king_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">King</span></p></body></html>"))
        self.queen_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Queen</span></p></body></html>"))
        self.poker_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Poker</span></p></body></html>"))
        self.solar_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Solar</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAdmin.setTitle(_translate("MainWindow", "Admin"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


